name: torchtemp
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - pytorch-cuda=11.6
  - pip
  - pip:
      - -r requirements.txt
      - -e .
